# Generated by Django 4.0.4 on 2022-06-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=10)),
                ('no_of_worker', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
