# Generated by Django 4.0.5 on 2022-06-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_no', models.IntegerField()),
                ('bed_no', models.IntegerField()),
                ('phone_no', models.IntegerField()),
                ('address', models.CharField(max_length=10)),
            ],
        ),
    ]
